package org.iis.plagiarismdetector.settings;

public enum PARAMETER {
	PARAMETERS_BM25_K1, PARAMETERS_BM25_b, PARAMETERS_LM_DIRICHLET_MU, PARAMETERS_JM_LAMBDA, PARAMETERS_DIRICHKET_MIU, PARAMETERS_LM_JM_LAMBDA
}